version: "3.7"
networks:
  internal:
    driver: "bridge"

services:
  api:
    build:
      context: api
      target: development
    volumes:
      - ./api:/var/www/html
      - /var/www/html/node_modules
    networks:
      - internal
    ports:
      # This map host port to container port 80
      - "${DOCKER_API_PORT:-3000}:80"
    restart: always

  web:
    build:
      context: web
      target: development
    volumes:
      - ./web:/var/www/html
      - /var/www/html/node_modules
    networks:
      - internal
    ports:
      # This map host port to container port 80
      - "${DOCKER_WEB_PORT:-5000}:80"
    environment:
      PORT: 80
    restart: always
